pull_request_rules:
  - name: Apply patches on `master`
    conditions:
      - label=apply-on-master
    actions:
      backport:
        branches:
          - master
        assignees:
          - "{{ author }}"
  - name: Apply patches on `3.20.x`
    conditions:
      - label=apply-on-3-20-x
    actions:
      backport:
        branches:
          - 3.20.x
        assignees:
          - "{{ author }}"
  - name: Apply patches on `3.19.x`
    conditions:
      - label=apply-on-3-19-x
    actions:
      backport:
        branches:
          - 3.19.x
        assignees:
          - "{{ author }}"
  - name: Apply patches on `3.18.x`
    conditions:
      - label=apply-on-3-18-x
    actions:
      backport:
        branches:
          - 3.18.x
        assignees:
          - "{{ author }}"          
